version: "3.8"

services:
  db:
    image: postgres:13
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: smartrent
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - default

  main_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: main_service
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - default

  user_service:
    build:
      context: ./user_service
      dockerfile: Dockerfile
    container_name: user_service
    ports:
      - "8001:8001"
    depends_on:
      - db
    networks:
      - default

  report_service:
    build:
      context: ./report_service
      dockerfile: Dockerfile
    container_name: report_service
    ports:
      - "8002:8002"
    depends_on:
      - main_service
    networks:
      - default

  edge_uplink:
    build:
      context: ./device_service/edge_uplink
    container_name: edge_uplink
    environment:
      - EVENT_HUB_CONN_STR=${EVENT_HUB_CONN_STR}
      - EVENT_HUB_NAME=${EVENT_HUB_NAME}
      - TARGET_BASE_URL=http://localhost:8000/sensors
    networks:
      - default

  edge_downlink:
    build:
      context: ./device_service/edge_downlink
    container_name: edge_downlink
    environment:
      - IOTHUB_CONNECTION_STRING=${IOTHUB_CONNECTION_STRING}
    ports:
      - "5005:5000"
    networks:
      - default

volumes:
  pgdata:

networks:
  default:
    driver: bridge
