apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: report-service
  template:
    metadata:
      labels:
        app: report-service
    spec:
      containers:
        - name: report-service
          image: pbl6acr.azurecr.io/report_service:latest
          ports:
            - containerPort: 8002
---
apiVersion: v1
kind: Service
metadata:
  name: report-service
spec:
  type: LoadBalancer
  ports:
    - port: 8002
      targetPort: 8002
  selector:
    app: report-service
