services:
  sensor_server:
    build:
      context: ./sensor_server
    container_name: sensor_server
    devices:
      - /dev/gpiomem
    environment:
      # - POST_URL=http://localhost:5000/post  # comment to be offline
      - POST_INTERVAL=5
    ports:
      - "5000:5000"
  command_server:
    build:
      context: ./command_server
    container_name: command_server
    depends_on:
      - sensor_server
