services:
  sensor_server:
    build:
      context: ./sensor_server
    container_name: sensor_server
    devices:
      - /dev/gpiomem
    environment:
      - POST_INTERVAL=5
      - DHT_INTERVAL=3
  upload_server:
    build:
      context: ./upload_server
    container_name: upload_server
    depends_on:
      - sensor_server
    environment:
      - POST_URL=http://edge_uplink:5000/data  # Comment to be offline
  download_server:
    build:
      context: ./download_server
    container_name: download_server
    depends_on:
      - sensor_server
    # ports:
    #   - "5000:5000"
networks:
  default:
    external: true
    name: shared-net
